config/routes.rb
Oilexpert::Application.routes.draw do

  root :to => 'welcome#home'

  resources :dummies

  resources :users
  match ':controller(/:action)'

  match 'users/:id/groups' => 'users#groups'

  resources :groups

end

app/models/dummy.rb
class Dummy < ActiveRecord::Base
end

app/controllers/dummies_controller.rb
class DummiesController < ApplicationController
  # GET /dummies
  # GET /dummies.xml
  def index
    @dummies = Dummy.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dummies }
    end
  end

  # GET /dummies/1
  # GET /dummies/1.xml
  def show
    @dummy = Dummy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dummy }
    end
  end

  # GET /dummies/new
  # GET /dummies/new.xml
  def new
    @dummy = Dummy.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dummy }
    end
  end

  # GET /dummies/1/edit
  def edit
    @dummy = Dummy.find(params[:id])
  end

  # POST /dummies
  # POST /dummies.xml
  def create
    @dummy = Dummy.new(params[:dummy])

    respond_to do |format|
      if @dummy.save
        format.html { redirect_to(@dummy, :notice => 'Dummy was successfully created.') }
        format.xml  { render :xml => @dummy, :status => :created, :location => @dummy }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dummy.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dummies/1
  # PUT /dummies/1.xml
  def update
    @dummy = Dummy.find(params[:id])

    respond_to do |format|
      if @dummy.update_attributes(params[:dummy])
        format.html { redirect_to(@dummy, :notice => 'Dummy was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dummy.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dummies/1
  # DELETE /dummies/1.xml
  def destroy
    @dummy = Dummy.find(params[:id])
    @dummy.destroy

    respond_to do |format|
      format.html { redirect_to(dummies_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/dummies_helper.rb
module DummiesHelper
end

app/views/dummies/_form.html.erb
<%= form_for(@dummy) do |f| %>
  <% if @dummy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dummy.errors.count, "error") %> prohibited this dummy from being saved:</h2>

      <ul>
      <% @dummy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dummies/edit.html.erb
<h1>Editing dummy</h1>

<%= render 'form' %>

<%= link_to 'Show', @dummy %> |
<%= link_to 'Back', dummies_path %>

app/views/dummies/index.html.erb
<h1>Listing dummies</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dummies.each do |dummy| %>
  <tr>
    <td><%= link_to 'Show', dummy %></td>
    <td><%= link_to 'Edit', edit_dummy_path(dummy) %></td>
    <td><%= link_to 'Destroy', dummy, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dummy', new_dummy_path %>

app/views/dummies/new.html.erb
<h1>New dummy</h1>

<%= render 'form' %>

<%= link_to 'Back', dummies_path %>

app/views/dummies/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_dummy_path(@dummy) %> |
<%= link_to 'Back', dummies_path %>